image: python:3.10-slim

services:
  - name: docker:20.10.16-dind
    alias: docker

stages:
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - apt-get update && apt-get install -y curl git openssh-client make docker.io
  - mkdir -p ~/.docker/cli-plugins
  - curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
  - chmod +x ~/.docker/cli-plugins/docker-compose
  - docker compose version
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan $STAGING_HOST >> ~/.ssh/known_hosts

deploy_stage:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - when: never
  script:
    - make run.prod
