image: python:3.10-slim

services:
  - name: docker:20.10.16-dind
    alias: docker

stages:
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  PLAYBOOK_DEST: /home/"$STAGING_USERNAME"/playbooks/fp-service

before_script:
  - apt-get update && apt-get install -y openssh-client
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan "$STAGING_HOST" >> ~/.ssh/known_hosts
  - ssh -i ~/.ssh/id_rsa "$STAGING_USERNAME"@"$STAGING_HOST" 'echo SSH OK'
  - python3 -m pip install -r requirements/requirements-cicd.txt

deploy_stage:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: always
    - when: never
  script:
    - ansible-playbook -i cicd/inventory.ini cicd/deploy.yaml

destroy_stage:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
      when: always
    - when: never
  script:
    - ansible-playbook -i cicd/inventory.ini cicd/destroy.yaml
